<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMxiTX0w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMxiTX0w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMxiTX0w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMxiTX0w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMxiTX0w\App_KernelDevDebugContainer([
    'container.build_hash' => 'MxiTX0w',
    'container.build_id' => 'c8074ebe',
    'container.build_time' => 1733037681,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMxiTX0w');
